### ISSUE TITLE
stability

### ISSUE THREAD

**Issue by theofidry** [Happyr/GoogleApiBundle#10]
I'm wishing to develop a Symfony2 application embracing Google Apps for Businesses. So I was looking for a bundle to help with that: is this bundle still experimental or is it stable enough?

**Comment by Nyholm** [comment]
This bundle is just a simple wrapper for the google api client. It does not do much... so yes. =)

**Comment by theofidry** [comment]
Ok great :) But I'm a bit surprised by the stats: only 9 stars an 9 forks and the only other bundle I found is [isometriks](https://github.com/isometriks/GoogleApiBundle). Since it is only a wrapper it makes sense that there is not much code produced, PR and issues. Did I miss something or maybe people don't bother with a bundle for that?

**Comment by Nyholm** [comment]
I believe people don't really bother. This bundle does only provide a neat way to handle the configuration. The only important class is the [Client](https://github.com/Happyr/GoogleApiBundle/blob/master/Services/GoogleClient.php) and then here is how I created a service out of the analytics class: https://github.com/Happyr/GoogleApiBundle/blob/master/Services/AnalyticsService.php

**Comment by theofidry** [comment]
Okay, thanks for your quick answer!
