### ISSUE TITLE
Make it compatible with Symfony 3.0

### ISSUE THREAD

**Issue by kilhage** [Happyr/GoogleApiBundle#14]
Is it planned to make this Bundle compatible with Symfony 3.0?

**Comment by smedbergsimon** [comment]
+1

**Comment by Nyholm** [comment]
That would be great. Which deprecated functions are we using?

**Comment by kilhage** [comment]
Not sure if you are using any, it needs to be tested and composer.json needs to be updated to something similar to:

```json
        "symfony/framework-bundle": "2.*|~3.0",
```

**Comment by Nyholm** [comment]
Okey, Send a PR and we could all test it.

**Comment by diriy** [comment]
Is it possible to use this bundle for Symfony3 right now or not? Thank you in advance!
