### ISSUE TITLE
How to construct the Google API service object ?

### ISSUE THREAD

**Issue by LionelPaulus** [Happyr/GoogleApiBundle#21]
Hi,

I'm trying to use your bundle to get access to the Google Calendar API.
I've figured the scope and accessToken validation but how can I construct the service object ?
In the [Google documentation](https://developers.google.com/google-apps/calendar/quickstart/php), they say to do this:
```php
$service = new Google_Service_Calendar($client);
```

But if I do that with your bundle, I have this error:
> Attempted to load class "Google_Service_Calendar" from namespace "AppBundle\Controller". Did you forget a "use" statement for another namespace?

Thanks in advance !
Lionel

**Comment by grago** [comment]
I think you need to do: 

$service = new \Google_Service_Calendar($client->getGoogleClient());

**Comment by LionelPaulus** [comment]
Thanks for your reply!
I finally did that, it worked but I suppose we don't use **GoogleApiBundle** anymore with this solution?
```php
$service = new \Google_Service_Calendar(new \Google_Client());
```

**Comment by grago** [comment]
I think that if you use $client->getGoogleClient() (as i previously posted) instead of constructing a new client, you will be using the client GoogleApiBundle provides.

**Comment by LionelPaulus** [comment]
Yes you are certainly right, thanks for your answer! :)
