### ISSUE TITLE
google/apiclient version

### ISSUE THREAD

**Issue by Airborn22** [Happyr/GoogleApiBundle#7]
Hi @Nyholm,

I've seen that your bundle requires google/apiclient v1.0.1-beta although the version of the latest google/apiclient is 1.1.2
Is there any chance that your bundle will support this version?

Thank you,
Alex

**Comment by Nyholm** [comment]
Resolved in #9

**Comment by garak** [comment]
Ehi @Nyholm, couple of days is past. In my project, everything is fine: can you release a new tag? Maybe a 2.0.1 tag?

**Comment by Nyholm** [comment]
Just pushed 2.1.0.

**Comment by garak** [comment]
Thank you!
So, you should change your dev-master alias to something like "2.2.x-dev"

**Comment by Nyholm** [comment]
Thank you. I forgot about that.

https://github.com/Happyr/GoogleApiBundle/commit/274627863c32a1be5476d4c9581970ce7d754580
